add week1 tasks
alinazar77/B34_GR10_JavaCodingTasks pull request #4
Opened 2024-05-22 18:38 UTC by IdeenNova

could you review and approve please?

2024-05-22 18:40 UTC, alinazar77 approved these changes

2024-05-22 23:20 UTC, alinazar77 commented on .gitignore
gitignore supposed to be changed as well? just double check

2024-05-22 23:21 UTC, alinazar77 requested changes
Are the .gitignore supposed to be update as well? @IdeenNova

2024-05-23 13:41 UTC, TahminaZ approved these changes

2024-05-23 13:42 UTC, TahminaZ commented
Approved from my side

2024-05-23 15:28 UTC, alinazar77 approved these changes

2024-05-23 15:30 UTC, merged